class Methods():

    def __init__(self):
        self.attrs = ['primary', 'secondary']
        self.primary = [
      "bake",
      "boil",
      "broil",
      "blanch",
      "microwave",
      "stir-fry",
      "fry",
      "pressure cook",
      "grill",
      "simmer",
      "blend",
      "sear",
      "steam",
      "saute",
      "poach",
      "deep-fry",
      "shallow-fry",
      "roast",
      "slow-cook",
      "slow cook"
    ]
        self.secondary = [
      "arrange",
      "add",
      "bake",
      "beat",
      "boil",
      "brush",
      "cover",
      "cool",
      "combine",
      "cream",
      "cut",
      "crush",
      "dip",
      "drain",
      "dry",
      "chill",
      "crumble",
      "flour",
      "flip",
      "fold",
      "grease",
      "grate",
      "heat",
      "line",
      "mash",
      "measure",
      "mix",
      "melt",
      "pour",
      "garnish",
      "preheat",
      "pound",
      "layer",
      "stuff",
      "knead",
      "refrigerate",
      "rinse",
      "saute",
      "serve",
      "season",
      "shake",
      "squeeze",
      "simmer",
      "sift",
      "slice",
      "soak",
      "spoon",
      "spread",
      "sprinkle",
      "stir",
      "strain",
      "toast",
      "toss",
      "turn",
      "whisk",
      "coat",
      "place",
      "rub",
      "lower"
    ]

    def __str__(self):
        result = ''
        for x in self.attrs:
            result += f'{x}: {getattr(self, x)}; \n'
        return result