class Style():

    def __init__(self):
        self.attrs = ['chinese', 'mexican', 'cajun', 'indian', 'french', 'german', 'other']
        self.chinese = {
            "fry":"stir-fry",
            "saute":"stir-fry",
            "sear":"stir-fry",
            "soak":"boil",
            "immerse":"braise",
            "bath":"braise",
            "broil":"roast",
            "grill":"roast",
            "bake":"steam",
            "fork":"chopsticks",
            "spoon":"cooking shovel",
            "pan":"wok",
            "tray":"wok",
            "oven":"steamer",
            "chili":"dried chili",
            "hot pepper":"chili powder",
            "pepper":"white pepper",
            "spice":"five spice powder",
            "parsley":"bay leaf",
            "coriander":"bay leaf",
            "seasoning":"parsley",
            "salt":"soy sauce",
            "lemon":"vinegar",
            "olive oil": "sesame oil",
            "butter":"sesame oil",
            "starch":"cornstarch",
            "bbq sauce":"oyster sauce",
            "ketchup":"hosin sauce",
            "cabbage":"napa cabbage",
            "mushroom":"shiitake mushroom",
            "mushrooms":"shiitake mushrooms",
            "cinnamon":"chinese five spice",
            "tomato sauce":"chilli bean sauce",
            "red chilli sauce":"chilli bean sauce",
            "mayonnaise":"chilli bean sauce",
            "mayo":"chilli bean sauce",
            "red wine":"shaoxing rice wine",
            "vinegar":"white rice vinegar",
            "pasta":"dried egg noodles",
            "spaghetti":"dried egg noodles",
            "noodles":"vermicelli noodles"
      }
        self.mexican = {
            "bake":"roast",
            "wok":"plancha",
            "griddle":"plancha",
            "broil":"roast",
            "oven":"steamer",
            "spoon":"spatula",
            "pasta":"pinto",
            "spaghetti":"black beans",
            "flour":"rice flour",
            "potato":"avocado",
            "potatoes":"avocado",
            "basil":"cilantro",
            "parsley":"cilantro",
            "lemon":"lime",
            "soy sauce":"vinegar",
            "ketchup":"salsas",
            "broccoli":"corn",
            "cauliflower":"corn",
            "hot pepper":"jalapenos",
            "beef":"pork",
            "miripoix":"soffrito",
            "steak":"pork",
            "macaroni":"rice",
            "lasagne":"rice",
            "chiles":"guajillo chiles",
            "cinnamon":"mexican cinnamon",
            "chocolate":"mexican chocolate",
            "butter":"lard",
            "vegetable oil":"lard"
      }
        self.cajun = {
            "stir-fry":"saute",
            "steam":"smoke",
            "chopsticks": "fork",
            "steamer": "smoker",
            "miripoix": "holy trinity",
            "soffrito": "holy trinity",
            "carrot": "bell pepper",
            "roux": "dark roux",
            "shallot": "green onion",
            "chili": 'cayenne',
            "sausage": "andouille",
            "chorizo": "boudin",
            "pork": "boar",
            "pork belly": "salt pork",
            "stew": "gumbo",
            "rice": "dirty rice"
        }
        self.indian = {
            "steam":"dum (Indian steam)",
            "temper":"Tadka/Baghar (Indian temper)",
            "saut":"Bhunao (Indian saute)",
            "saute":"Bhunao (Indian saute)",
            "smoke":"Dhuanaar (Indian smoke)",
            "fry":"Talina/Talna (Indian deep fry)",
            "roast":"Tandoori (Indian roast)",
            "soak":"boil",
            "immerse":"braise",
            "bath":"braise",
            "broil":"roast",
            "grill":"roast",
            "bake":"dum (Indian steam)",
            "fork":"chopsticks",
            "spoon":"cooking shovel",
            "pan":"wok",
            "tray":"wok",
            "oven":"steamer",
            "container":"stainless steel spice container",
            "box":"stainless steel spice container",
            "pesetle": "stainless steel mortar",
            "spoon": "grinder",
            "blender": "strainer",
            "pot": "deep fry pan",
            "pan": "deep fry pan",
            "knive": "stainless stell knive",
            "chili":"dried chili",
            "hot pepper":"chili powder",
            "pepper":"black pepper",
            "spice":"cardamom",
            "parsley":"cassia bark",
            "coriander":"cassia bark",
            "seasoning":"cumin",
            "salt":"nutmeg and mace",
            "lemon":"vinegar",
            "olive oil": "sesame oil",
            "butter":"sesame oil",
            "starch":"cornstarch",
            "bbq sauce":"oyster sauce",
            "tomato sauce":"hoisin sauce",
            "ketchup":"hosin sauce",
            "cabbage":"napa cabbage",
            "mushroom":"shiitake mushroom",
            "mushrooms":"shiitake mushrooms",
            "tomato sauce":"chilli bean sauce",
            "red chilli sauce":"chilli bean sauce",
            "mayonnaise":"chilli bean sauce",
            "mayo":"chilli bean sauce",
            "vinegar":"white rice vinegar",
            "pasta":"dried egg noodles",
            "spaghetti":"dried egg noodles"
      }
        self.french = {
            "flavor":"bouquet garni",
            "cut":"chiffonade cut",
            "drizzle":"coulis",
            "loose":"déglacer",
            "degalz":"déglacer",
            "reduc":"demi-glace",
            "prepare":"en papillote",
            "vegetable":"julienne vegetable",
            "brais":"mirepoix",
            "simmer":"mirepoix",
            "put":"mise en place",
            "thicken":"roux",
            "whisk":"roux",
            "fry":"sauté",
            "knife":"fish spatula",
            "board":"rimmed baking sheet",
            "pan":"braising pans",
            "tray":"rimmed baking sheet",
            "pot":"non-stick skillets",
            "paper":"silicone baking mat",
            "towel":"linen kitchen towels",
            "oven": "dutch oven",
            "bowl": "ramekins",
            "dish": "oval baking dish",
            "oil":"olive oil",
            "mustard":"dijon mustard",
            "salt":"fleur de sel",
            "cream":"crème fraîche",
            "mushroom":"herves de provence",
            "onion":"shallots",
            "garlic":"shallots",
            "bread":"french bread",
            "cheese":"french cheese"
      }
        self.german = {
            "sour cream":"schmandt",
            "beef":"veal",
            "fennel":"caraway"
      }
        self.other = {
            "sugar":"honey",
            "white sugar":"honey",
            "brown sugar":"honey",
            "sour cream":"greek yogurt",
            "flour":"whole wheat flour",
            "butter":"margarine",
            "whole milk":"skim milk",
            "peanut butter":"powdered peanut",
            "baking powder":"baking soda",
            "chocolate":"cocoa",
            "cream cheese":"fat-free cream",
            "mayonnaise":"plain yogurt",
            "mayo":"plain yogurt",
            "white bread":"wheat bread",
            "sausage":"bacon",
            "egg":"egg white",
            "pasta":"whole grain pasta",
            "spaghetti":"whole grain spaghetti",
            "potato":"cauliflower",
            "potatoes":"cauliflowers",
            "pork":"beef",
            "noodles":"zucchini noodles",
            "potato chips":"popcorn",
            "ranch dressing":"balsamic vinegar",
            "salami":"low-sodium ham",
            "pickle":"cucumber",
            "cheese":"low-fat cheese",
            "margarine":"diet margarine",
            "turkey bacon":"fresh turkey stripes",
            "beef":"lamb",
            "soy sauce":"low-sodium soy sauce",
            "clams":"oyster mushroom",
            "mussels":"oyster mushroom",
            "oysters":"oyster mushroom",
            "scallops":"oyster mushroom",
            "shrimp":"fish",
            "lobster":"crab",
            "crayfish":"oyster mushroom",
            "crab":"shrimp",
            "clams":"fish",
            "honey":"sugar",
            "sweet potato":"potato",
            "chicken":"pork",
            "salmon":"pork",
            "mushroom":"pork",
            "milk":"creamer",
            "bacon":"sausage",
            "hummus":"mayo",
            "broccoli":"potato",
            "bell pepper":"bacon",
            "cauliflower":"potato",
            "edamame":"sausage",
            "chickpeas":"sausage",
            "carrot":"potato",
            "jam":"sugar",
            "olive oil":"vegetable oil",
            "nuts":"chocolate",
            "greek yogurt":"sour cream",
            "cinnamon":"sugar",
            "applesauce":"sugar",
            "maple syrup":"sugar",
            "beer":"chicken broth",
            "bread crumbs":"cracker crumbs",
            "brown sugar":"white sugar",
            "evaporated milk":"light cream",
            "lemon grass":"lemon zest",
            "onion":"shallots",
            "orange zest":"orange juice",
            "vinegar":"lemon juice",
            "wine":"beef broth",
            "yogurt":"sour cream"
}

    def __str__(self):
        result = ''
        for x in self.attrs:
            dic = getattr(self, x)
            result += f'{x}: '
            for key, value in dic.items():
                result += 'key -> value, '
            result += f'; \n'
        return result
