class Tools():

    def __init__(self):
        self.attrs = ['tool']
        self.tool = [
    "apple corer",
    "apple cutter",
    "bag",
    "baking sheet",
    "balloon whisk",
    "basket skimmer",
    "baster",
    "basting brush",
    "beanpot",
    "bell whisk",
    "bench knife",
    "bench scraper",
    "biscuit mould",
    "blender",
    "blow torch",
    "blowlamp",
    "blowtorch",
    "boil oven preventer",
    "bottle opener",
    "bowl",
    "bread knife",
    "browning bowl",
    "browning plate",
    "browning tray",
    "bulb baster",
    "burger spatula",
    "burr grinder",
    "burr mill",
    "buscuit cutter",
    "buscuit press",
    "butcher's twine",
    "butter curler",
    "cake server",
    "cake shovel",
    "can opener",
    "candy thermometer",
    "carving knife",
    "cheese cutter",
    "cheese grater",
    "cheese knife",
    "cheese knives",
    "cheese slicer",
    "cheese spreader",
    "cheesecloth",
    "chef knife",
    "chef's knife",
    "chefs knife",
    "cherry pitter",
    "chinois",
    "chinoise",
    "citrus reamer",
    "clay pot",
    "cleaver",
    "colander",
    "cookie cutter",
    "cookie mould",
    "cookie press",
    "cooking twine",
    "corkscrew",
    "crab cracker",
    "cup",
    "cutting board",
    "deep spoon",
    "dish",
    "dough scraper",
    "drum sieve",
    "dutch oven",
    "edible tableware",
    "egg piercer",
    "egg poacher",
    "egg separator",
    "egg slicer",
    "egg timer",
    "fat separator",
    "fillet knife",
    "fish scaler",
    "fish slice",
    "fish spatula",
    "flat coil whisk",
    "flat whisk",
    "flour sifter",
    "food mill",
    "food storage container",
    "french whisk",
    "frying pan",
    "funnel",
    "fryer",
    "garlic press",
    "grapefruit knife",
    "grater",
    "gravy separator",
    "gravy strainer",
    "gravy whisk",
    "griddle",
    "herb chopper",
    "honey dipper",
    "ice cream scoop",
    "kitchen mallet",
    "kitchen scale",
    "kitchen scissor",
    "kitchen scraper",
    "kitchen string",
    "kitchen tool crock",
    "kitchen twine",
    "knife",
    "ladle",
    "lame",
    "lemon reamer",
    "lemon squeezer",
    "lobster fork",
    "lobster pick",
    "mandoline",
    "mashers",
    "mated colander pot",
    "measuring cup",
    "measuring jar",
    "measuring jug",
    "measuring spoon",
    "meat grinder",
    "meat tenderiser",
    "meat tenderizer",
    "meat thermometer",
    "melon ball",
    "melon baller",
    "metal tong",
    "mezzaluna",
    "microplane",
    "milk frother",
    "milk guard",
    "milk watcher",
    "mincer",
    "mini whisk",
    "mixing bowl",
    "mixing whisk",
    "molcajete",
    "mortar",
    "nutcracker",
    "nutmeg grater",
    "olive stoner",
    "oven glove",
    "oven mitt",
    "oven",
    "pan",
    "panini spatula",
    "pasta fork",
    "pastry bag",
    "pastry blender",
    "pastry brush",
    "pastry wheel",
    "paper towel",
    "peeler",
    "pepper grinder",
    "pepper mill",
    "pestle",
    "pie bird",
    "pie cutter",
    "pie funnel",
    "pie server",
    "pie vent",
    "pizza cutter",
    "pizza shovel",
    "pizza slicer",
    "pot holder",
    "pot minder",
    "pot",
    "pot-holder",
    "potato masher",
    "potato ricer",
    "potholder",
    "poultry shears",
    "ricer",
    "roast lifter",
    "roller docker",
    "rolling pin",
    "salt shaker",
    "santoku knife",
    "saucepan",
    "scale",
    "scissor",
    "scoop",
    "scraper",
    "serrated bread knife",
    "serving platter",
    "shredder",
    "sieve",
    "sifter",
    "silicone tong",
    "skillet",
    "slotted spoon",
    "spatula",
    "spider strainer",
    "spider",
    "spoon sieve",
    "spoon skimmer",
    "steak knife",
    "stove",
    "strainer",
    "sugar thermometer",
    "slow cooker",
    "tablespoon",
    "tamis",
    "teaspoon",
    "tin opener",
    "tomato knife",
    "tong",
    "trussing needle",
    "turner",
    "twine",
    "urokotori",
    "utility knife",
    "vegetable peeler",
    "weighing scales",
    "whisk",
    "wooden spoon",
    "zester",
    "nonstick spray"
]

    def __str__(self):
        result = ''
        for x in self.attrs:
            result += f'{x}: {getattr(self, x)}; \n'
        return result